<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AssemblyName>CairnStoryTracker</AssemblyName>
    <RootNamespace>CairnStoryTracker</RootNamespace>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <DebugType>embedded</DebugType>
    <Version>0.1.0</Version>
  </PropertyGroup>

  <PropertyGroup>
    <!-- Override with -p:GameDir="..." or the CAIRN_GAME_DIR environment variable -->
    <GameDir Condition="'$(GameDir)' == ''">$(CAIRN_GAME_DIR)</GameDir>
    <InteropDir>$(GameDir)\MelonLoader\Il2CppAssemblies</InteropDir>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="MelonLoader">
      <HintPath>$(GameDir)\MelonLoader\net6\MelonLoader.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Il2CppInterop.Runtime">
      <HintPath>$(GameDir)\MelonLoader\net6\Il2CppInterop.Runtime.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Il2CppTheGameBakers.Cairn.Global">
      <HintPath>$(InteropDir)\Il2CppTheGameBakers.Cairn.Global.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Il2CppTheGameBakers.Cairn.Utilities.SingletonBase">
      <HintPath>$(InteropDir)\Il2CppTheGameBakers.Cairn.Utilities.SingletonBase.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Il2CppTheGameBakers.Cairn.Utilities">
      <HintPath>$(InteropDir)\Il2CppTheGameBakers.Cairn.Utilities.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Il2Cppmscorlib">
      <HintPath>$(InteropDir)\Il2Cppmscorlib.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Il2CppTheGameBakers.TGBTools.StringId.Generated.Runtime">
      <HintPath>$(InteropDir)\Il2CppTheGameBakers.TGBTools.StringId.Generated.Runtime.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Il2CppTheGameBakers.TGBTools.Localization.Runtime">
      <HintPath>$(InteropDir)\Il2CppTheGameBakers.TGBTools.Localization.Runtime.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Il2CppTheGameBakers.TGBTools.Common.Runtime">
      <HintPath>$(InteropDir)\Il2CppTheGameBakers.TGBTools.Common.Runtime.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Il2CppTheGameBakers.TGBTools.UI.Runtime">
      <HintPath>$(InteropDir)\Il2CppTheGameBakers.TGBTools.UI.Runtime.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>$(InteropDir)\Unity.TextMeshPro.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>$(InteropDir)\UnityEngine.UI.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.TextRenderingModule">
      <HintPath>$(InteropDir)\UnityEngine.TextRenderingModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.UIModule">
      <HintPath>$(InteropDir)\UnityEngine.UIModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Unity.Addressables">
      <HintPath>$(InteropDir)\Unity.Addressables.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(InteropDir)\UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>$(InteropDir)\UnityEngine.PhysicsModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Unity.InputSystem">
      <HintPath>$(InteropDir)\Unity.InputSystem.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="CairnAPI">
      <HintPath>$(GameDir)\Mods\CairnAPI.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

</Project>
